name: Deploy storybook to GitHub Pages

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "stable"

    - name: Install dependencies
      run: npm install

    - name: Build storybook
      run: npm run build-storybook

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages
        folder: storybook-static
        token: ${{ secrets.github_token }}